version: '3'
services:
  usersmicroservice:
    container_name: "usersMicroService"
    build: ./usersMicroService/.
    depends_on:
      - rabbit1
    ports:
      - "8081:8081"
    command: go run main.go
    volumes:
      - ./usersMicroService:/go/src/usersMicroService
      - ./db:/go/src/db
    working_dir: /go/src/usersMicroService
    environment:
      GOPATH: /go
  phoenix:
    container_name: "phoenix"
    build: ./phoenix/.
    depends_on:
      - rabbit1
    ports:
      - "8080:8080"
    command: go run main.go
    volumes:
      - ./phoenix:/go/src/phoenix
      - ./db:/go/src/db
    working_dir: /go/src/phoenix
    environment:
      GOPATH: /go
  readapi:
    container_name: "readApi"
    build: ./readApi/.
    command: go run main.go
    volumes:
      - ./readApi:/go/src/readApi
    environment:
      GOPATH: /go
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672-15682:15672"
      - "5672-5682:5672"
    labels:
      NAME: "rabbitmq1"